# TUNABLE PARAMS
import os

# Passing
PASSING_RANGE_X = -0.2 #float(os.environ["PASSING_RANGE_X"]) 

# Shooting
SHOT_RANGE_X = float(os.environ["SHOT_RANGE_X"]) #0.7
SHOT_RANGE_Y = float(os.environ["SHOT_RANGE_Y"]) #0.2

# UNTUNABLE PARAMS
GRAVITY = 0.098
PICK_HEIGHT = 0.5
STEP_LENGTH = 0.015
BODY_RADIUS = 0.012
SLIDE_THRESHOLD = STEP_LENGTH + BODY_RADIUS
ENEMY_GOAL = [1, 0]
INF = 999