# TUNABLE PARAMS
# Passing
PASSING_RANGE_X = -0.2

# Shooting
SHOT_RANGE_X = 0.7
SHOT_RANGE_Y = 0.185
LONG_SHOT_X = 0.4
LONG_SHOT_Y = 0.2
GOALKEEPER = 0
GOALIE_OUT = 0.2
SHOT_TRIGGERING_RADIUS = 0.15
shot_range = [[SHOT_RANGE_X, 1], [-SHOT_RANGE_Y, SHOT_RANGE_Y]]

# UNTUNABLE PARAMS
GRAVITY = 0.098
PICK_HEIGHT = 0.5
STEP_LENGTH = 0.015
BODY_RADIUS = 0.012
SLIDE_THRESHOLD = STEP_LENGTH + BODY_RADIUS
ENEMY_GOAL = [1, 0]
INF = 999
prev_has_ball = True

def modify(x):
	global prev_has_ball
	prev_has_ball = x